CREATE TABLE game (id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1)  PRIMARY KEY NOT NULL, 
	          	   creator BIGINT,
	          	   CONSTRAINT fk_creator FOREIGN KEY (creator) REFERENCES dominion_user(id));
	          
	          
CREATE TABLE game_history (id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY NOT NULL,
						   game_id BIGINT,
						   game_file VARCHAR (512),
						   date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
						   CONSTRAINT fk_game_id FOREIGN KEY (game_id) REFERENCES game(id));
						   
CREATE TABLE rel_players_game (game_id BIGINT,
							   player_id BIGINT,
							   CONSTRAINT fk_game_id FOREIGN KEY (game_id) REFERENCES game(id),
							   CONSTRAINT fk_player_id FOREIGN KEY (player_id) REFERENCES player(id));
							   
CREATE TABLE player (id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY NOT NULL,
					 score SMALLINT,
					 buys TINYINT,
					 actions TINYINT,
					 display_name VARCHAR[50],
					 player_type TINYINT);
			
CREATE TABLE ref_cards (id SMALLINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY NOT NULL,
					    title VARCHAR(64),
					    instructions VARCHAR(256));
					 
CREATE TABLE rel_player_user (user_id BIGINT,
							  player_id BIGINT,
							  CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES dominion_user(id),
							  CONSTRAINT fk_player_id FOREIGN KEY (player_id) REFERENCES player(id));
							  
CREATE TABLE rel_player_deck (player_id BIGINT,
							  
							  
CREATE TABLE rel_treasure_cards_game (card_id SMALLINT,
									  game_id BIGINT,
									  card_count TINYINT,
									  CONSTRAINT fk_card_id FOREIGN KEY (card_id) REFERENCES ref_card(id),
									  CONSTRAINT fk_game_id FOREIGN KEY (game_id) REFERENCES game(id));

CREATE TABLE rel_trash_game (card_id SMALLINT,
							 game_id BIGINT,
							 CONSTRAINT fk_card_id FOREIGN KEY (card_id) REFERENCES ref_card(id),
							 CONSTRAINT fk_game_id FOREIGN KEY (game_id) REFERENCES game(id));
							 
CREATE TABLE rel_victory_card_game (card_id SMALLINT,
							 	    game_id BIGINT,
							 	    card_count TINYINT,
							 		CONSTRAINT fk_card_id FOREIGN KEY (card_id) REFERENCES ref_card(id),
							 		CONSTRAINT fk_game_id FOREIGN KEY (game_id) REFERENCES game(id));
							 
CREATE TABLE rel_kingdom_cards_game (card_id SMALLINT,
							 	     game_id BIGINT,
							 	     card_count TINYINT,
							 		 CONSTRAINT fk_card_id FOREIGN KEY (card_id) REFERENCES ref_card(id),
							 		 CONSTRAINT fk_game_id FOREIGN KEY (game_id) REFERENCES game(id));

CREATE TABLE rel_curses_game (game_id BIGINT,
							  card_count TINYINT,
							  CONSTRAINT fk_game_id FOREIGN KEY (game_id) REFERENCES game(id));
							  

							  